[package]
name = "kv-storage"
version = "0.1.0"
edition = "2024"
authors = ["stackinspector"]
license = "MPL-2.0"
repository = "https://github.com/Berylsoft/kv-storage"

[lib]
name = "kv_storage"
path = "lib.rs"

[dependencies]
rusqlite = { git = "https://github.com/Berylsoft/rusqlite-cksumvfs", version = "0.40.1-cksumvfs", features = ["bundled", "blob", "cksumvfs"] }
crc32fast = "1.5.0"
bytes = { version = "1", optional = true }
foundations = { git = "https://github.com/Berylsoft/foundations", features = ["const-concat"] }
actor-core = { git = "https://github.com/Berylsoft/actor", optional = true }

[features]
actor = ["bytes", "actor-core"]
